# -*- coding: utf-8 -*-
"""Arabic_Meeting_Summarizer_with_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVf1T9We7HWXJZPk0aSb0po9T3_YO871

# 🎙️ Arabic Meeting Summarizer — Hybrid Edition
### ASR: Faster-Whisper large-v3-turbo · Diarization: Simple Clustering · Summary: **Mistral Saba 24B (فهم عربي) + Gemini 2.5 Flash (تقرير هيكلي)**

---

## 🗺️ Pipeline

```
YouTube URL / Local File
         ↓
[Cell 1] Install all packages (run once per session)
         ↓
[Cell 2] RAM / GPU monitor helpers
         ↓
[Cell 3] ⚙️  CONFIGURATION  ← set your URL & API keys here
         ↓
[Cell 4] Download audio from YouTube → WAV
         ↓
[Cell 5] Pre-process audio: 16 kHz · mono · normalize · chunk
         ↓
[Cell 6] ASR — Faster-Whisper large-v3-turbo → Arabic transcript + Simple Diarization
         ↓
[Cell 7] Hybrid Summary — Mistral Saba يفهم النص العربي كاملاً + Gemini 2.5 Flash يبني التقرير
         ↓
[Cell 8] Display rich HTML output + Export TXT / JSON / MD
         ↓
[Cell 9] Free GPU / RAM memory
```

> ⚠️ **شغّل الخلايا واحدة تلو الأخرى — لا تستخدم "Run All"**

---

## 🔑 الخطوات المطلوبة قبل التشغيل

### 1. 🔑 Gemini API Key (مطلوب)
- اذهب إلى [aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey)
- سجّل الدخول بحساب Google
- اضغط **"Create API key"** واحفظ المفتاح
- في Colab: اضغط أيقونة 🔑 في الشريط الجانبي → أضف سراً باسم `GEMINI_API_KEY`
- أو الصقه مباشرة في Cell 3

### 2. 🔑 Mistral API Key (مطلوب لـ Mistral Saba)
- اذهب إلى [console.mistral.ai/api-keys](https://console.mistral.ai/api-keys)
- سجّل الدخول وأنشئ مفتاح API جديد
- في Colab: أيقونة 🔑 → أضف سراً باسم `MISTRAL_API_KEY`
- أو الصقه مباشرة في Cell 3

### 3. 🖥️ GPU Runtime (موصى به بشدة)
- في Colab: **Runtime → Change runtime type → T4 GPU**
- Whisper (النقل الصوتي) يعمل أسرع بكثير على GPU — Mistral Saba وGemini يعملان عبر API السحابي ولا يحتاجان GPU

### ✅ Mistral Saba 24B — نموذج مخصص للعربية ومنطقة الشرق الأوسط، متاح عبر Mistral AI API الرسمي (يتطلب مفتاح API)
"""

# ════════════════════════════════════════
# CELL 1 — Install all required packages (run once per session)
# ════════════════════════════════════════
import sys

# Install system-level FFmpeg development libraries
!apt-get update -qq
!apt-get install -qq build-essential libavformat-dev libavcodec-dev libavdevice-dev \
    libavfilter-dev libavutil-dev libswscale-dev libpostproc-dev libswresample-dev

# Upgrade pip
!{sys.executable} -m pip install -q --upgrade pip

# Install ctranslate2 compatible with numpy 2.x
!{sys.executable} -m pip install -q --no-cache-dir "ctranslate2>=3.25.0" --force-reinstall

# Install all required packages
!{sys.executable} -m pip install -q --no-cache-dir \
    faster-whisper \
    yt-dlp \
    imageio-ffmpeg \
    soundfile \
    torchaudio \
    psutil \
    markdown2 \
    "google-genai>=1.64.0,<2.0.0" \
    "google-auth==2.47.0" \
    openai \
    huggingface_hub \
    transformers \
    accelerate

print("✅ جميع الحزم جاهزة — الآن اضغط Runtime → Restart session")

# ════════════════════════════════════════════════════
# CELL 2 — RAM / GPU monitor + memory-free helpers
# ════════════════════════════════════════════════════
import psutil, torch, gc, os

# Suppress TensorFlow/Flax warnings
os.environ["TRANSFORMERS_NO_TF_IMPORT"]   = "1"
os.environ["TRANSFORMERS_NO_FLAX_IMPORT"] = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"]        = "3"

def show_ram():
    ram = psutil.virtual_memory()
    filled = int(ram.percent / 5)
    bar = '█' * filled + '░' * (20 - filled)
    print(f'RAM  [{bar}] {ram.used/1e9:.1f}/{ram.total/1e9:.1f} GB  ({ram.percent:.0f}%)')
    if torch.cuda.is_available():
        alloc = torch.cuda.memory_allocated() / 1e9
        total = torch.cuda.get_device_properties(0).total_memory / 1e9
        print(f'GPU  {alloc:.1f}/{total:.1f} GB  |  CUDA {torch.version.cuda}')
    else:
        print('GPU  not available — CPU mode (slower, but works)')

def free_memory(*model_vars):
    """Delete model variables and flush GPU cache."""
    for v in model_vars:
        try:
            del v
        except Exception:
            pass
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print('🧹 Memory freed')

show_ram()

# ════════════════════════════════════════════════════
# هذه الخلية لم تعد مطلوبة — الإعداد كله في Cell 3 أدناه
# ════════════════════════════════════════════════════
print("✅ تخطّ هذه الخلية وانتقل إلى Cell 3 (CONFIGURATION)")

# ════════════════════════════════════════════════════
# CELL 3 — ⚙️ CONFIGURATION
# ════════════════════════════════════════════════════
from datetime import datetime
import os

# ── رابط الاجتماع ──────────────────────────────────
YOUTUBE_URL = "https://www.youtube.com/watch?v=oueP7_CBIoo"
#https://www.youtube.com/shorts/ABUMwh8VMdE
# غيّر الرابط أعلاه حسب الحاجة

# ── السرعة والجودة ─────────────────────────────────
USE_FAST_MODE = True      # True = أسرع، False = أدق

# ── عدد المتحدثين ──────────────────────────────────
NUM_SPEAKERS_HINT = None  # None = تلقائي، أو ضع رقماً مثل 2 أو 3

# ── نموذج عربي: Mistral Saba (24B — مخصص للعربية والمنطقة، عبر API الرسمي) ──
ARABIC_MODEL_BASE_URL = "https://api.mistral.ai/v1"
ARABIC_MODEL_ID = "mistral-saba-latest"   # أو "mistral-saba-2502" — تحقق من console.mistral.ai

# ── مفاتيح API ─────────────────────────────────────
try:
    from google.colab import userdata
    ARABIC_MODEL_API_KEY = userdata.get('MISTRAL_API_KEY') or ""
    GEMINI_API_KEY       = userdata.get('GEMINI_API_KEY')  or ""
    print('✅ API keys loaded from Colab Secrets')
except Exception:
    ARABIC_MODEL_API_KEY = ""   # ← الصق مفتاح Mistral هنا مباشرة
    GEMINI_API_KEY       = ""   # ← الصق مفتاح Gemini هنا مباشرة
    print('⚠️  Colab Secrets غير متاح — الصق المفاتيح أعلاه')

if not ARABIC_MODEL_API_KEY:
    print("❌ ARABIC_MODEL_API_KEY فارغ — Cell 7 ستفشل. أضف مفتاح Mistral قبل المتابعة.")
else:
    print(f"✅ Arabic model API Key جاهز | Model: {ARABIC_MODEL_ID}")

if not GEMINI_API_KEY:
    print("❌ GEMINI_API_KEY فارغ — Cell 7 ستفشل. أضف المفتاح قبل المتابعة.")

# ── مسارات الإخراج ─────────────────────────────────
OUTPUT_DIR = "./meeting_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)
SESSION = datetime.now().strftime('%Y%m%d_%H%M%S')
print(f"✅ Fast Mode: {USE_FAST_MODE} | Session: {SESSION}")
print(f"✅ Arabic model: {ARABIC_MODEL_ID}")

# ════════════════════════════════════════════════════
# CELL 4 — Download audio from YouTube → WAV
# ════════════════════════════════════════════════════
import os
import yt_dlp
import imageio_ffmpeg
from pathlib import Path

free_memory()

FFMPEG_BIN = imageio_ffmpeg.get_ffmpeg_exe()
print(f"⏳ Downloading audio ...")

ydl_opts = {
    "format": "bestaudio/best",
    "outtmpl": f"{OUTPUT_DIR}/{SESSION}_%(title)s.%(ext)s",
    "ffmpeg_location": FFMPEG_BIN,
    "postprocessors": [{
        "key": "FFmpegExtractAudio",
        "preferredcodec": "wav",
        "preferredquality": "192",
    }],
    "quiet": False,
    "no_warnings": True,
    "socket_timeout": 30,
    "extractor_args": {"youtube": {"player_client": ["android", "web"]}},
}

AUDIO_PATH = None

def _find_wav():
    wavs = sorted(Path(OUTPUT_DIR).glob(f'{SESSION}_*.wav'))
    return str(wavs[-1]) if wavs else None

try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(YOUTUBE_URL, download=True)
    AUDIO_PATH = _find_wav()
    if not AUDIO_PATH:
        raise FileNotFoundError("WAV file not found after download")
    print(f"✅ Download successful: {info.get('title', 'Unknown')}")
    size_mb = os.path.getsize(AUDIO_PATH) / 1e6
    print(f"📁 Audio file ready: {AUDIO_PATH}  ({size_mb:.1f} MB)")
except Exception as e:
    print(f"❌ Download failed: {e}")
    print("   Tip: Check the URL in Cell 3, or upload a local audio file manually.")

import gc
import os
import numpy as np
import soundfile as sf
import torch
import torchaudio.transforms as T
import imageio_ffmpeg
import yt_dlp
from pathlib import Path

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# ── Auto-retry download if Cell 4 failed ─────────────────────────────────────
if not globals().get("AUDIO_PATH"):
    print("⚠️  AUDIO_PATH not found — retrying download ...")
    FFMPEG_BIN = imageio_ffmpeg.get_ffmpeg_exe()
    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": f"{OUTPUT_DIR}/{SESSION}_%(title)s.%(ext)s",
        "ffmpeg_location": FFMPEG_BIN,
        "postprocessors": [{"key": "FFmpegExtractAudio",
                            "preferredcodec": "wav", "preferredquality": "192"}],
        "quiet": True,
        "socket_timeout": 30
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.extract_info(YOUTUBE_URL, download=True)
        wavs = sorted(Path(OUTPUT_DIR).glob(f'{SESSION}_*.wav'))
        AUDIO_PATH = str(wavs[-1]) if wavs else None
        if AUDIO_PATH:
            print(f"✅ تم التنزيل: {AUDIO_PATH}")
        else:
            raise FileNotFoundError("WAV not found after retry")
    except Exception as e:
        raise RuntimeError(f"❌ Download failed: {e} — check the URL in Cell 3")

print("⏳ Processing audio ...")

# 1. Load
audio_array, sample_rate = sf.read(AUDIO_PATH, dtype='float32')
print(f'   Loaded — {sample_rate} Hz | shape: {audio_array.shape}')

# 2. Convert to Mono
if audio_array.ndim > 1:
    audio_array = np.mean(audio_array, axis=1)
    print('   Converted to Mono')

# 3. Resample to 16 kHz
TARGET_SR = 16000
if sample_rate != TARGET_SR:
    print(f'   Resampling: {sample_rate} Hz → {TARGET_SR} Hz ...')
    audio_tensor = torch.from_numpy(audio_array.copy()).float()
    resampler = T.Resample(orig_freq=int(sample_rate), new_freq=TARGET_SR)
    audio_array = resampler(audio_tensor).numpy()
    sample_rate = TARGET_SR
    print('   ✅ Resampling complete')

# 4. Peak Normalization
peak = np.abs(audio_array).max()
if peak > 0:
    audio_array = audio_array / (peak + 1e-8)

DURATION_SEC = len(audio_array) / TARGET_SR
DURATION_MIN = DURATION_SEC / 60
print(f'✅ Processed: {DURATION_MIN:.1f} min | {TARGET_SR} Hz | Mono')

# 5. Save processed file
PROCESSED_WAV = f"{OUTPUT_DIR}/{SESSION}_processed.wav"
sf.write(PROCESSED_WAV, audio_array, TARGET_SR, subtype='PCM_16')
print(f'   Saved processed file: {PROCESSED_WAV}')

show_ram()

# ════════════════════════════════════════════════════
# CELL 6 — Faster-Whisper ASR (Arabic) + Simple Diarization
# ════════════════════════════════════════════════════
import json
import gc
import sys
import numpy as np
import torch
from faster_whisper import WhisperModel

# Increase recursion limit for deep numpy/ctranslate2 initialization
sys.setrecursionlimit(2000)

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# ── Device selection ──────────────────────────────────
DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"
COMPUTE    = "float16" if DEVICE == "cuda" else "int8"
BEAM_SIZE  = 3 if USE_FAST_MODE else 5

print(f"🖥️  Device: {DEVICE} | Compute: {COMPUTE} | Beam size: {BEAM_SIZE}")

# ── Load Whisper model ────────────────────────────────
print("⏳ Loading Faster-Whisper large-v3-turbo ...")
asr_model = WhisperModel(
    "large-v3-turbo",
    device=DEVICE,
    compute_type=COMPUTE,
)
print("✅ ASR model loaded")

# ── Transcription ─────────────────────────────────────
print("⏳ Transcribing (this may take several minutes) ...")
segments_iter, info = asr_model.transcribe(
    PROCESSED_WAV,
    language="ar",
    beam_size=BEAM_SIZE,
    vad_filter=True,
    vad_parameters={"min_silence_duration_ms": 500},
)
print(f"   Detected language: {info.language} (prob={info.language_probability:.2f})")

# Materialise segments
segments = list(segments_iter)
print(f"   ✅ Got {len(segments)} segments")

# ── Simple speaker diarization ─────────────────────────
# Uses pause-length heuristic: long pause → speaker change
def simple_diarize(segs, pause_threshold: float = 1.5, max_speakers: int = 6):
    """Assign speaker labels based on inter-segment pauses."""
    speaker_id = 0
    prev_end    = 0.0
    labelled    = []
    for seg in segs:
        if seg.start - prev_end > pause_threshold:
            speaker_id = (speaker_id + 1) % max_speakers
        labelled.append({
            "speaker": f"Speaker_{speaker_id + 1}",
            "start":   round(seg.start, 2),
            "end":     round(seg.end,   2),
            "text":    seg.text.strip(),
        })
        prev_end = seg.end
    return labelled

# Override max speakers if user provided a hint
max_spk = NUM_SPEAKERS_HINT if NUM_SPEAKERS_HINT else 6
diarized_segments = simple_diarize(segments, max_speakers=max_spk)

# ── Build full transcript ──────────────────────────────
transcript_lines = [
    f"[{s['speaker']}] ({s['start']}s - {s['end']}s): {s['text']}"
    for s in diarized_segments
]
full_transcript = "\n".join(transcript_lines)

print(f"\n📜 Transcript preview (first 5 segments):")
for line in transcript_lines[:5]:
    print("  ", line)

# ── Save transcript files ─────────────────────────────
TRANSCRIPT_TXT  = f"{OUTPUT_DIR}/{SESSION}_transcript.txt"
TRANSCRIPT_JSON = f"{OUTPUT_DIR}/{SESSION}_transcript.json"

with open(TRANSCRIPT_TXT, "w", encoding="utf-8") as f:
    f.write(full_transcript)
with open(TRANSCRIPT_JSON, "w", encoding="utf-8") as f:
    json.dump(diarized_segments, f, ensure_ascii=False, indent=2)

print(f"\n💾 Transcript saved: {TRANSCRIPT_TXT}")
print(f"💾 JSON saved:       {TRANSCRIPT_JSON}")
print(f"\n✅ Total segments: {len(diarized_segments)} | Characters: {len(full_transcript)}")

show_ram()

# ════════════════════════════════════════════════════
# CELL 7 — Hybrid Summary: Mistral Saba (فهم عربي) + Gemini (تقرير هيكلي)
# ════════════════════════════════════════════════════
import gc, torch, os, time
from openai import OpenAI
import google.genai as genai

os.environ["TRANSFORMERS_NO_TF_IMPORT"]   = "1"
os.environ["TRANSFORMERS_NO_FLAX_IMPORT"] = "1"

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

if 'full_transcript' not in globals() or not full_transcript.strip():
    raise RuntimeError("❌ full_transcript فارغ — شغّل Cell 6 أولاً")
if not GEMINI_API_KEY:
    raise ValueError("❌ GEMINI_API_KEY غير موجود")
if not ARABIC_MODEL_API_KEY:
    raise ValueError("❌ ARABIC_MODEL_API_KEY غير موجود")

# ═══════════════════════════════════════════════════
# A) إعداد النموذج العربي (Mistral Saba) عبر API الرسمي (OpenAI-compatible)
# ═══════════════════════════════════════════════════
arabic_client = OpenAI(
    api_key=ARABIC_MODEL_API_KEY,
    base_url=ARABIC_MODEL_BASE_URL,
)
print(f"✅ Arabic model API جاهز | {ARABIC_MODEL_BASE_URL} | Model: {ARABIC_MODEL_ID}")

# ═══════════════════════════════════════════════════
# B) إعداد Gemini 2.5 Flash
# ═══════════════════════════════════════════════════
gemini_client = genai.Client(api_key=GEMINI_API_KEY)
print("✅ Gemini 2.5 Flash جاهز")

# ═══════════════════════════════════════════════════
# C) دوال المعالجة
# ═══════════════════════════════════════════════════
def arabic_model_understand(full_text: str, max_chars: int = 10000) -> str:
    """Mistral Saba يقرأ النص العربي كاملاً ويستخرج المعلومات الجوهرية."""
    truncated = full_text[:max_chars]
    messages = [
        {
            "role": "system",
            "content": (
                "أنت مساعد متخصص في تحليل اجتماعات العمل باللغة العربية الفصيحة. "
                "مهمتك استخراج المعلومات الجوهرية من نص الاجتماع بدقة عالية."
            ),
        },
        {
            "role": "user",
            "content": (
                f"حلّل نص الاجتماع التالي واستخرج:\n"
                f"1. المواضيع الرئيسية التي نوقشت\n"
                f"2. القرارات المتخذة مع ذكر المسؤول عن كل قرار\n"
                f"3. المهام الموكلة لكل شخص والمواعيد النهائية\n"
                f"4. النقاط الخلافية أو غير المحسومة\n"
                f"5. أسماء المشاركين والأدوار إن وُجدت\n\n"
                f"نص الاجتماع:\n{truncated}"
            ),
        },
    ]
    response = arabic_client.chat.completions.create(
        model=ARABIC_MODEL_ID,
        messages=messages,
        max_tokens=1200,
        temperature=0.3,
    )
    return response.choices[0].message.content.strip()


def gemini_report(arabic_analysis: str, full_text: str, max_chars: int = 12000) -> str:
    """Gemini يبني التقرير الهيكلي بناءً على تحليل النموذج العربي."""
    arabic_section = (
        f"**تحليل Mistral Saba العربي للاجتماع:**\n{arabic_analysis}\n\n"
        if arabic_analysis else ""
    )
    prompt = f"""أنت محلل اجتماعات محترف متخصص باللغة العربية.

{arabic_section}**النص الكامل للاجتماع:**
{full_text[:max_chars]}

أنشئ تقريراً شاملاً واحترافياً بالتنسيق التالي بالضبط:

## 1. جدول القرارات الرئيسية
| # | القرار | التفاصيل | المسؤول | الموعد |
|---|--------|----------|---------|--------|

## 2. جدول المهام والمسؤوليات
| # | المهمة | المسؤول | الموعد | الأولوية |
|---|--------|---------|--------|----------|

## 3. أبرز النقاط المطروحة
- نقطة 1
- نقطة 2
- نقطة 3

## 4. خريطة ذهنية
- **الموضوع الرئيسي**: ...
  - **فرع 1**: ...
  - **فرع 2**: ...
  - **فرع 3**: ...

## 5. الخلاصة التنفيذية
(5-7 أسطر موجزة تصف محور الاجتماع ونتائجه)

ابدأ مباشرة بالعنوان الأول دون أي مقدمة.
"""
    for attempt in range(5):
        try:
            response = gemini_client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )
            return response.text.strip()
        except Exception as e:
            if "503" in str(e) or "UNAVAILABLE" in str(e):
                wait = 20 * (attempt + 1)
                print(f"   ⏳ Gemini مشغول، انتظر {wait}ث ({attempt+1}/5)...")
                time.sleep(wait)
            else:
                raise e
    raise RuntimeError("❌ Gemini غير متاح بعد 5 محاولات")


def hybrid_summary(full_text: str) -> str:
    """Mistral Saba يفهم → Gemini يبني التقرير."""
    print("🔍 Mistral Saba: جاري قراءة وتحليل النص العربي كاملاً ...")
    try:
        arabic_analysis = arabic_model_understand(full_text)
        print(f"   ✅ Mistral Saba أنتج {len(arabic_analysis)} حرف من التحليل")
    except Exception as e:
        print(f"   ⚠️  Mistral Saba فشل: {e}")
        arabic_analysis = ""

    print("🧠 Gemini: جاري بناء التقرير الهيكلي ...")
    final_report = gemini_report(arabic_analysis, full_text)
    print(f"   ✅ Gemini أنتج {len(final_report)} حرف")
    return final_report


# ═══════════════════════════════════════════════════
# D) تشغيل الخط الكامل
# ═══════════════════════════════════════════════════
print("\n🤖 بدء التلخيص الهجين: Mistral Saba API + Gemini 2.5 Flash ...")
summary_text = hybrid_summary(full_transcript)

# حفظ النتائج
SUMMARY_MD  = f"{OUTPUT_DIR}/{SESSION}_summary.md"
SUMMARY_TXT = f"{OUTPUT_DIR}/{SESSION}_summary.txt"

with open(SUMMARY_MD,  "w", encoding="utf-8") as f:
    f.write(summary_text)
with open(SUMMARY_TXT, "w", encoding="utf-8") as f:
    f.write(summary_text)

print(f"\n💾 Markdown محفوظ: {SUMMARY_MD}")
print(f"💾 TXT محفوظ:       {SUMMARY_TXT}")

# ════════════════════════════════════════════════════
# CELL 8 — Display results as rich HTML
# ════════════════════════════════════════════════════
import markdown2
from IPython.display import display, HTML

if 'summary_text' not in globals() or not summary_text.strip():
    print("❌ summary_text not found — make sure Cell 7 ran successfully")
else:
    # Convert Markdown → HTML
    try:
        summary_html = markdown2.markdown(
            summary_text,
            extras=["tables", "fenced-code-blocks", "strike", "cuddled-lists"]
        )
    except Exception:
        # simple fallback
        summary_html = summary_text.replace('\n', '<br>')

    display(HTML(f"""
    <div dir="rtl" style="
        font-family: 'Segoe UI', Tahoma, Arial, sans-serif;
        direction: rtl;
        text-align: right;
        padding: 28px 32px;
        background: linear-gradient(135deg, #f8f9fa 0%, #e9f7ef 100%);
        border-radius: 18px;
        border: 2px solid #28a745;
        margin: 12px 0;
        box-shadow: 0 4px 16px rgba(40,167,69,0.12);
    ">
        <h2 style="color:#1a6e35; margin-bottom:6px;">
            📋 الملخص النهائي — Mistral Saba + Gemini 2.5 Flash
        </h2>
        <p style="color:#666; font-size:13px; margin-top:0;">
            Session: {SESSION}
        </p>
        <hr style="border-color:#c3e6cb;">
        <div style="line-height:1.9; font-size:15.5px; color:#1a1a1a;">
            {summary_html}
        </div>
    </div>
    """))

    print("\n─── Raw text preview ───")
    print(summary_text[:2000] + ("..." if len(summary_text) > 2000 else ""))

"""## 🔗 RAG Chatbot Integration

Indexes this session's transcript + summary into the Meeting RAG Chatbot,
then lets you ask questions about it directly in this notebook.

Requires the RAG chatbot project to be on  (e.g. )
with its dependencies installed.
"""

from google.colab import files
import os, zipfile

uploaded = files.upload()  # select meeting-rag-chatbot-integrated.zip
with zipfile.ZipFile(list(uploaded.keys())[0], 'r') as z:
    z.extractall('/content/project')

os.chdir('/content/project')
print("Files ready:", os.listdir('.'))

!pip install fastapi uvicorn[standard] python-multipart pydantic pydantic-settings \
    langchain langchain-community langchain-google-genai langchain-core \
    faiss-cpu sentence-transformers rank-bm25 \
    loguru diskcache langdetect pypdf python-docx chromadb -q

from google.colab import userdata
import os
os.environ['GEMINI_API_KEY'] = userdata.get('GEMINI_API_KEY')

import os
print("Exists:", os.path.exists('/content/project'))
print("Contents:", os.listdir('/content/project') if os.path.exists('/content/project') else "N/A")

import sys
import importlib.util

print("sys.path entries containing 'project':")
for p in sys.path:
    if 'project' in p:
        print(" ", repr(p))

print()
print("Looking for backend module spec:")
spec = importlib.util.find_spec('backend')
print(spec)

print()
print("Does __init__.py exist?")
import os
print(os.path.exists('/content/project/backend/__init__.py'))
print("Size:", os.path.getsize('/content/project/backend/__init__.py'))

print(sys.path)

import importlib
import sys

importlib.invalidate_caches()

spec = importlib.util.find_spec('backend')
print(spec)

!pip uninstall langchain langchain-community langchain-core langchain-google-genai -y -q
!pip install langchain==0.2.1 langchain-community==0.2.1 langchain-core==0.2.3 langchain-google-genai==1.0.5 -q

import subprocess
result = subprocess.run(['find', '/content', '-maxdepth', '3', '-type', 'd', '-name', 'meeting_output'], capture_output=True, text=True)
print(result.stdout)

result = ingest_summarizer_session(SESSION, "/content/meeting_output")
print(result)

import os
print(os.listdir('/content/meeting_output'))

import os
print("Current working dir:", os.getcwd())

result = ingest_summarizer_session(SESSION, "/content/meeting_output")
print(result)

result = ingest_summarizer_session(SESSION, "/content/meeting_output")
print(result)

import os
os.environ['LLM_MODEL'] = 'gemini-2.5-flash'

result = ingest_summarizer_session(SESSION, "/content/meeting_output")

result = ingest_summarizer_session(SESSION, "/content/meeting_output")
print(result)

answer, sources = await ask("ما هي القرارات التي تم اتخاذها؟")
print(answer)

from backend.retriever import retrieve
from backend.ingest_from_summarizer import _hybrid_retriever

results = retrieve("القرارات الرئيسية المتخذة في الاجتماعات", hybrid_retriever=_hybrid_retriever)
print("Number of results:", len(results))
for doc, score in results[:5]:
    print(score, "-", doc.page_content[:100])

from backend.vectorstore import delete_vectorstore
delete_vectorstore()

# re-import to reset module-level state too
import importlib
import backend.ingest_from_summarizer as ifs
importlib.reload(ifs)

result = ifs.ingest_summarizer_session(SESSION, "/content/meeting_output")
print(result)

results = retrieve("القرارات", hybrid_retriever=ifs._hybrid_retriever)
print(len(results))

import sys
import importlib

sys.path.append("/content/project")

# تأكد من تحديث موديل Gemini قبل أي إعادة بناء
import os
os.environ['LLM_MODEL'] = 'gemini-2.5-flash'

from backend.config import get_settings
get_settings.cache_clear()

# امسح أي بيانات قديمة متراكمة من محاولات سابقة
from backend.vectorstore import delete_vectorstore
delete_vectorstore()

import backend.ingest_from_summarizer as ifs
importlib.reload(ifs)

# استخدم المسار المطلق الصحيح لمجلد السمرايزر
result = ifs.ingest_summarizer_session(SESSION, "/content/meeting_output")
print(result)

answer, sources = await ifs.ask("ما هي القرارات التي تم اتخاذها؟")
print(answer)

answer, sources = await ifs.ask("ما هي القرارات التي تم اتخاذها؟")
print("Answer:", answer)
print()
print("Sources:", sources)

from backend.retriever import retrieve
results = retrieve("القرارات الرئيسية المتخذة في الاجتماعات", hybrid_retriever=ifs._hybrid_retriever)
print("Number of results:", len(results))
for doc, score in results[:5]:
    print(round(score, 4), "-", doc.page_content[:100])

from backend.chat import ChatEngine
import diskcache

cfg = get_settings()
cache = diskcache.Cache(cfg.cache_dir)
cache.clear()
print("Cache cleared.")

answer, sources = await ifs.ask("ما هي القرارات التي تم اتخاذها؟")
print(answer)

answer, sources = await ifs.ask("ما هو الموضوع الرئيسي للاجتماع؟")
print(answer)

answer, sources =await ifs.ask("قل لي القرار الاخير")
print(answer)

# ════════════════════════════════════════════════════
# CELL 10 — Free GPU / RAM memory
# ════════════════════════════════════════════════════
import gc, torch

for var in ['al_pipe', 'asr_model', 'gemini_model']:
    if var in globals():
        try:
            del globals()[var]
        except Exception:
            pass

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

show_ram()
print("✅ Memory freed — pipeline complete 🎉")

"""## 📊 تقييم جودة الملخص (Summary Evaluation)

يقيّم هذا القسم جودة `summary_text` الناتج من Cell 7 باستخدام ثلاث مقاييس مكمّلة لبعضها:

| المقياس | النوع | يقيس ماذا |
|---|---|---|
| **ROUGE-1/2/L** | تطابق لغوي (Lexical) | نسبة تطابق الكلمات/التتابعات بين الملخص والمرجع |
| **BERTScore** | تشابه دلالي (Semantic) | تشابه المعنى عبر نماذج لغوية — يتحمّل اختلاف الصياغة |
| **LLM-as-a-Judge** | تقييم شبيه بالبشر | يقيّم Gemini الدقة، الشمولية، التماسك، الإيجاز، وجودة اللغة |

> 💡 **ملاحظة مهمة:** ROUGE و BERTScore يحتاجان مرجعًا (Reference) للمقارنة. إن كان لديك **ملخص مرجعي بشري (Gold Summary)**، ضعه في `REFERENCE_SUMMARY` بالخلية التالية للحصول على نتائج دقيقة وذات معنى. إن تركته فارغًا، سيُستخدم النص الكامل للاجتماع (`full_transcript`) كمرجع تقريبي فقط (نتائج تقريبية وغير دقيقة بنفس الشكل).
"""

# ════════════════════════════════════════════════════
# EVAL 1 — 📦 تثبيت مكتبات التقييم
# ════════════════════════════════════════════════════
import sys
!{sys.executable} -m pip install -q rouge-score bert-score
print("✅ مكتبات التقييم جاهزة: rouge-score, bert-score")

# ════════════════════════════════════════════════════
# EVAL 2 — ⚙️ إعدادات التقييم (ملخص مرجعي اختياري)
# ════════════════════════════════════════════════════
# إن كان لديك ملخص مرجعي (Gold Summary) كتبه إنسان، ضعه هنا بين علامتي """ ... """
# هذا يجعل نتائج ROUGE و BERTScore أكثر دقة وذات معنى.
# إن تركته فارغًا، سيُستخدم النص الكامل للاجتماع (full_transcript) كمرجع تقريبي.
REFERENCE_SUMMARY = """
""".strip()

if 'summary_text' not in globals() or not summary_text.strip():
    raise RuntimeError("❌ summary_text غير موجود — شغّل خلية التلخيص (Cell 7) أولاً")
if 'full_transcript' not in globals() or not full_transcript.strip():
    raise RuntimeError("❌ full_transcript غير موجود — شغّل خلية النقل الصوتي (Cell 6) أولاً")

HAS_REFERENCE = bool(REFERENCE_SUMMARY)

if HAS_REFERENCE:
    print(f"📌 يوجد ملخص مرجعي ({len(REFERENCE_SUMMARY)} حرف) — سيُستخدم في ROUGE و BERTScore")
else:
    print("⚠️  لا يوجد ملخص مرجعي — سيُستخدم النص الكامل للاجتماع كمرجع تقريبي")
    print("   (للحصول على نتائج أدق، ضع ملخصًا مرجعيًا بشريًا في REFERENCE_SUMMARY أعلاه)")

# ════════════════════════════════════════════════════
# EVAL 3 — 📏 ROUGE (تطابق لغوي / Lexical Overlap)
# ════════════════════════════════════════════════════
import re
from rouge_score import rouge_scorer

# ── Tokenizer مخصص للعربية ──────────────────────────────
# المُجزّئ (tokenizer) الافتراضي في rouge_score يحذف كل الحروف غير اللاتينية
# (regex: [^a-z0-9]+) لذا نحتاج مُجزّئًا يدعم اليونيكود/العربية.
class ArabicTokenizer:
    _tashkeel = re.compile(r'[\u064B-\u0652\u0670\u0640]')  # تشكيل + تطويل

    def tokenize(self, text: str):
        text = self._tashkeel.sub('', text)
        return re.findall(r'\w+', text, flags=re.UNICODE)

rouge_reference = REFERENCE_SUMMARY if HAS_REFERENCE else full_transcript

scorer = rouge_scorer.RougeScorer(
    ['rouge1', 'rouge2', 'rougeL'],
    use_stemmer=False,
    tokenizer=ArabicTokenizer(),
)
rouge_scores = scorer.score(rouge_reference, summary_text)

label = "مقابل الملخص المرجعي" if HAS_REFERENCE else "مقابل النص الكامل (تقريبي)"
print(f"📏 ROUGE Scores — {label}")
print("─" * 60)
print(f"{'Metric':<10} | {'Precision':>10} | {'Recall':>10} | {'F1':>10}")
print("─" * 60)
for metric, s in rouge_scores.items():
    print(f"{metric.upper():<10} | {s.precision:>10.4f} | {s.recall:>10.4f} | {s.fmeasure:>10.4f}")

# ════════════════════════════════════════════════════
# EVAL 4 — 🧠 BERTScore (تشابه دلالي / Semantic Similarity)
# ════════════════════════════════════════════════════
import torch
from bert_score import score as bertscore_fn

bertscore_reference = REFERENCE_SUMMARY if HAS_REFERENCE else full_transcript

if not HAS_REFERENCE:
    print("⚠️  ملاحظة: BERTScore يقتصر فعليًا على أول ~512 توكن من كل نص — "
          "مقارنة الملخص بالنص الكامل لاجتماع طويل قد تعطي نتائج غير دقيقة.")

bs_device = "cuda" if torch.cuda.is_available() else "cpu"

# lang="ar" يختار نموذجًا متعدد اللغات مناسبًا للعربية تلقائيًا
P, R, F1 = bertscore_fn(
    [summary_text],
    [bertscore_reference],
    lang="ar",
    device=bs_device,
    verbose=True,
)

label = "مقابل الملخص المرجعي" if HAS_REFERENCE else "مقابل النص الكامل (تقريبي)"
print(f"\n🧠 BERTScore — {label}")
print("─" * 40)
print(f"{'Precision':<10}: {P.item():.4f}")
print(f"{'Recall':<10}: {R.item():.4f}")
print(f"{'F1':<10}: {F1.item():.4f}")

# ════════════════════════════════════════════════════
# EVAL 5 — ⚖️ LLM-as-a-Judge (تقييم شبيه بالبشر عبر Gemini)
# ════════════════════════════════════════════════════
import json, re, time

if 'gemini_client' not in globals():
    raise RuntimeError("❌ gemini_client غير موجود — شغّل خلية التلخيص (Cell 7) أولاً")


def llm_judge_evaluate(transcript: str, summary: str, reference: str = "", max_chars: int = 12000) -> dict:
    """يستخدم Gemini كـ'حكم' لتقييم جودة الملخص بطريقة شبيهة بالتقييم البشري."""

    reference_block = (
        f"\n**ملخص مرجعي (للمقارنة فقط):**\n{reference}\n"
        if reference else ""
    )

    judge_prompt = f"""أنت مقيّم خبير ومحايد لملخصات اجتماعات الأعمال باللغة العربية.

**النص الكامل للاجتماع (الحقيقة المرجعية):**
{transcript[:max_chars]}
{reference_block}
**الملخص المطلوب تقييمه:**
{summary}

قيّم الملخص أعلاه على المعايير التالية، كل معيار من 1 إلى 10:
1. faithfulness (الدقة والأمانة): هل المعلومات صحيحة وغير مُختلقة (لا Hallucination)؟
2. coverage (الشمولية): هل يغطي أهم القرارات والمهام والنقاط؟
3. coherence (التماسك والوضوح): هل التنظيم والصياغة مفهومة ومنطقية؟
4. conciseness (الإيجاز): هل الملخص موجز دون حشو أو تكرار؟
5. language_quality (جودة اللغة العربية): هل اللغة سليمة نحويًا وأسلوبيًا؟

أعد إجابتك بصيغة JSON فقط، بدون أي شرح أو نص خارج JSON، وبالشكل التالي بالضبط:
{{
  "faithfulness":     {{"score": 0, "justification": "..."}},
  "coverage":         {{"score": 0, "justification": "..."}},
  "coherence":        {{"score": 0, "justification": "..."}},
  "conciseness":      {{"score": 0, "justification": "..."}},
  "language_quality": {{"score": 0, "justification": "..."}},
  "overall_score": 0,
  "overall_comment": "..."
}}"""

    for attempt in range(5):
        try:
            response = gemini_client.models.generate_content(
                model="gemini-2.5-flash",
                contents=judge_prompt,
            )
            raw = response.text.strip()
            raw = re.sub(r"^```json\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()
            return json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"   ⚠️  فشل تحليل JSON من Gemini، إعادة المحاولة... ({e})")
        except Exception as e:
            if "503" in str(e) or "UNAVAILABLE" in str(e):
                wait = 20 * (attempt + 1)
                print(f"   ⏳ Gemini مشغول، انتظر {wait}ث ({attempt+1}/5)...")
                time.sleep(wait)
            else:
                raise e
    raise RuntimeError("❌ فشل تقييم LLM Judge بعد عدة محاولات")


print("⚖️  جاري تقييم الملخص باستخدام Gemini كحكم (LLM-as-a-Judge) ...")
judge_result = llm_judge_evaluate(full_transcript, summary_text, REFERENCE_SUMMARY)

print("\n📊 نتائج LLM Judge")
print("─" * 60)
criteria_ar = {
    "faithfulness":     "الدقة والأمانة",
    "coverage":         "الشمولية",
    "coherence":        "التماسك والوضوح",
    "conciseness":      "الإيجاز",
    "language_quality": "جودة اللغة",
}
for key, label in criteria_ar.items():
    item = judge_result.get(key, {})
    print(f"{label:<18} | {item.get('score', '-')}/10")
    print(f"   └─ {item.get('justification', '')}")

print("─" * 60)
print(f"{'التقييم العام':<18} | {judge_result.get('overall_score', '-')}/10")
print(f"   └─ {judge_result.get('overall_comment', '')}")

OUTPUT_DIR = "/content/meeting_output"

# ════════════════════════════════════════════════════
# EVAL 6 — 📋 تقرير التقييم النهائي + الحفظ
# ════════════════════════════════════════════════════
import json
from IPython.display import display, HTML

evaluation_report = {
    "session": SESSION,
    "has_reference_summary": HAS_REFERENCE,
    "rouge": {
        m: {"precision": s.precision, "recall": s.recall, "f1": s.fmeasure}
        for m, s in rouge_scores.items()
    },
    "bertscore": {
        "precision": float(P.item()),
        "recall": float(R.item()),
        "f1": float(F1.item()),
    },
    "llm_judge": judge_result,
}

EVAL_JSON = f"{OUTPUT_DIR}/{SESSION}_evaluation.json"
with open(EVAL_JSON, "w", encoding="utf-8") as f:
    json.dump(evaluation_report, f, ensure_ascii=False, indent=2)
print(f"💾 تقرير التقييم محفوظ: {EVAL_JSON}\n")

ref_note = "✅ مقارنة بملخص مرجعي بشري" if HAS_REFERENCE else "⚠️ ROUGE/BERTScore مقارنة تقريبية بالنص الكامل (لا يوجد مرجع بشري)"

display(HTML(f"""
<div dir="rtl" style="
    font-family: 'Segoe UI', Tahoma, Arial, sans-serif;
    direction: rtl;
    text-align: right;
    padding: 24px 28px;
    background: linear-gradient(135deg, #f8f9fa 0%, #eef3ff 100%);
    border-radius: 18px;
    border: 2px solid #4a6cf7;
    margin: 12px 0;
">
    <h2 style="color:#2a3eb1; margin-bottom:14px;">📊 تقرير تقييم الملخص</h2>
    <table style="width:100%; border-collapse:collapse; font-size:14.5px;">
        <tr style="background:#dde6ff;">
            <th style="padding:8px; text-align:right; border:1px solid #c5d1ff;">المقياس</th>
            <th style="padding:8px; text-align:center; border:1px solid #c5d1ff;">Precision</th>
            <th style="padding:8px; text-align:center; border:1px solid #c5d1ff;">Recall</th>
            <th style="padding:8px; text-align:center; border:1px solid #c5d1ff;">F1 / النتيجة</th>
        </tr>
        <tr>
            <td style="padding:8px; border:1px solid #c5d1ff;">ROUGE-1</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rouge1'].precision:.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rouge1'].recall:.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rouge1'].fmeasure:.3f}</td>
        </tr>
        <tr>
            <td style="padding:8px; border:1px solid #c5d1ff;">ROUGE-2</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rouge2'].precision:.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rouge2'].recall:.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rouge2'].fmeasure:.3f}</td>
        </tr>
        <tr>
            <td style="padding:8px; border:1px solid #c5d1ff;">ROUGE-L</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rougeL'].precision:.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rougeL'].recall:.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{rouge_scores['rougeL'].fmeasure:.3f}</td>
        </tr>
        <tr>
            <td style="padding:8px; border:1px solid #c5d1ff;">BERTScore</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{P.item():.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{R.item():.3f}</td>
            <td style="padding:8px; text-align:center; border:1px solid #c5d1ff;">{F1.item():.3f}</td>
        </tr>
        <tr style="background:#f0f4ff;">
            <td style="padding:8px; border:1px solid #c5d1ff;"><b>LLM Judge (عام)</b></td>
            <td colspan="3" style="padding:8px; text-align:center; border:1px solid #c5d1ff;"><b>{judge_result.get('overall_score','-')}/10</b> — {judge_result.get('overall_comment','')}</td>
        </tr>
    </table>
    <p style="color:#666; font-size:12.5px; margin-top:12px;">{ref_note}</p>
</div>
"""))